apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: cx-pipeline
spec:
  serviceName: qdrant
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.9.0
          ports:
            - containerPort: 6333
          readinessProbe:
            httpGet:
              path: /
              port: 6333
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 6333
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-storage
