"""
Topic clustering over stored feedback embeddings.

Algorithm:
  1. Export all embedding vectors + payloads from Qdrant
  2. Run KMeans (scikit-learn) with auto k selection via silhouette score
  3. Write cluster_id and cluster_label back to each Qdrant point's payload
  4. Generate human-readable cluster labels using the LLM (3-word phrases)

Auto k selection:
  Try k in [K_MIN, K_MAX], pick k with highest average silhouette score.
  Skipped if fewer than MIN_POINTS are stored.

Cluster labels are generated by feeding the top-3 summaries from each cluster
to the LLM and asking for a 3–5 word label. This is the only LLM call in the
entire module — all clustering math is deterministic.
"""
from __future__ import annotations

import os
import time
from typing import Optional

import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

from vectordb.client import ANALYSES_COLLECTION, get_client
from vectordb.retrieval import export_embeddings

K_MIN = int(os.getenv("CLUSTER_K_MIN", "3"))
K_MAX = int(os.getenv("CLUSTER_K_MAX", "12"))
MIN_POINTS = 20          # don't cluster if fewer than this many items
RANDOM_STATE = 42


# ── Auto k selection ──────────────────────────────────────────────────────────

def _best_k(X: np.ndarray) -> int:
    best_k, best_score = K_MIN, -1.0
    k_max = min(K_MAX, len(X) - 1)
    for k in range(K_MIN, k_max + 1):
        labels = KMeans(n_clusters=k, random_state=RANDOM_STATE, n_init=10).fit_predict(X)
        score = silhouette_score(X, labels, sample_size=min(500, len(X)))
        if score > best_score:
            best_score, best_k = score, k
    return best_k


# ── LLM label generation ──────────────────────────────────────────────────────

def _generate_label(summaries: list[str]) -> str:
    """Ask the LLM to produce a 3–5 word cluster label given sample summaries."""
    try:
        from analyzer.llm import get_llm
        prompt = (
            "Given these customer feedback summaries:\n"
            + "\n".join(f"- {s}" for s in summaries[:3])
            + "\n\nReply with ONLY a 3-5 word label describing the common theme. No punctuation."
        )
        llm = get_llm(temperature=0.1)
        return llm.invoke(prompt).content.strip()[:60]
    except Exception:
        return "Unlabelled cluster"


# ── Write cluster labels back to Qdrant ──────────────────────────────────────

def _write_cluster_labels(
    payloads: list[dict],
    labels: np.ndarray,
    cluster_labels: dict[int, str],
) -> None:
    """Patch cluster_id and cluster_label into each point's payload."""
    try:
        from qdrant_client.models import FieldCondition, Filter, MatchValue
        client = get_client()
        for payload, cluster_id in zip(payloads, labels):
            fid = payload.get("feedback_id")
            if not fid:
                continue
            client.set_payload(
                collection_name=ANALYSES_COLLECTION,
                payload={
                    "cluster_id": int(cluster_id),
                    "cluster_label": cluster_labels.get(int(cluster_id), ""),
                    "clustered_at": time.time(),
                },
                points=Filter(
                    must=[FieldCondition(key="feedback_id", match=MatchValue(value=fid))]
                ),
            )
    except Exception:
        pass


# ── Public API ─────────────────────────────────────────────────────────────────

def run_clustering(n_clusters: Optional[int] = None) -> dict:
    """
    Run topic clustering over all stored feedback embeddings.

    Returns a cluster report:
    {
        "n_clusters": int,
        "n_points": int,
        "silhouette_score": float,
        "clusters": [
            {"id": int, "label": str, "size": int, "sample_summaries": list[str]}
        ]
    }
    """
    vectors, payloads = export_embeddings(limit=5000)

    if len(vectors) < MIN_POINTS:
        return {
            "error": f"Not enough data — need at least {MIN_POINTS} feedback items, have {len(vectors)}.",
            "n_points": len(vectors),
        }

    X = np.array(vectors, dtype=np.float32)
    k = n_clusters or _best_k(X)
    k = max(K_MIN, min(k, len(X) - 1))

    km = KMeans(n_clusters=k, random_state=RANDOM_STATE, n_init=10)
    labels = km.fit_predict(X)
    sil = round(float(silhouette_score(X, labels, sample_size=min(500, len(X)))), 4)

    # Build per-cluster summary
    cluster_summaries: dict[int, list[str]] = {i: [] for i in range(k)}
    for payload, cluster_id in zip(payloads, labels):
        summary = payload.get("summary", "")
        if summary:
            cluster_summaries[int(cluster_id)].append(summary)

    # Generate LLM labels
    cluster_labels: dict[int, str] = {
        cid: _generate_label(summaries)
        for cid, summaries in cluster_summaries.items()
    }

    # Write back to Qdrant
    _write_cluster_labels(payloads, labels, cluster_labels)

    clusters = [
        {
            "id": cid,
            "label": cluster_labels[cid],
            "size": int(np.sum(labels == cid)),
            "sample_summaries": cluster_summaries[cid][:3],
        }
        for cid in range(k)
    ]
    clusters.sort(key=lambda c: c["size"], reverse=True)

    return {
        "n_clusters": k,
        "n_points": len(vectors),
        "silhouette_score": sil,
        "clustered_at": time.time(),
        "clusters": clusters,
    }
