"""Prometheus metrics for the analyzer pipeline.

Until now only the Rust producer/consumer exposed metrics (queue concurrency).
The Python analyzer was a black box — no latency percentiles, no cache visibility.
This module defines the analyzer-side metric objects; `api.py` mounts /metrics and
`main.py` + the pipeline stages record into them.

Histogram buckets are tuned for LLM-pipeline latencies (seconds, not milliseconds):
a single /analyze runs ~6-8 LLM calls so end-to-end p95 is multiple seconds.
"""

from __future__ import annotations

import time
from contextlib import contextmanager

from prometheus_client import Counter, Histogram

# Buckets in seconds — spread across the realistic LLM-pipeline latency range.
_LATENCY_BUCKETS = (0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 60.0)
# 0.0–1.0 in tenths — for score distributions (confidence, novelty).
_UNIT_BUCKETS = (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)

# Per-stage wall time (label distinguishes normalization / taxonomy / etc.).
PIPELINE_STAGE_DURATION = Histogram(
    "pipeline_stage_duration_seconds",
    "Wall-clock duration of a single pipeline stage",
    labelnames=("stage",),
    buckets=_LATENCY_BUCKETS,
)

# Full analyze_single wall time, split by whether the dedup cache short-circuited.
PIPELINE_REQUEST_DURATION = Histogram(
    "pipeline_request_duration_seconds",
    "End-to-end duration of analyze_single",
    labelnames=("outcome",),  # "cache_hit" | "computed"
    buckets=_LATENCY_BUCKETS,
)

# Dedup short-circuit accounting (the real cache lives in main.analyze_single).
DEDUP_CACHE_HITS = Counter(
    "dedup_cache_hits_total",
    "Feedback items served from a cached duplicate analysis (no LLM calls)",
)
DEDUP_CACHE_MISSES = Counter(
    "dedup_cache_misses_total",
    "Feedback items with no cached duplicate — full pipeline ran",
)

# ── Research-facing metrics ─────────────────────────────────────────────────────
# These quantify *system properties* a reviewer/researcher cares about, not just ops
# health: inference economics, model-cascade payoff, the dedup win, and calibration.

# LLM call accounting, split by the cascade tier ("big" Qwen-7B vs "small" 1.5B).
# Token counters let you derive tokens/request and tokens/sec (with stage latency).
LLM_CALLS_TOTAL = Counter("llm_calls_total", "LLM invocations made by the pipeline", labelnames=("model",))
LLM_PROMPT_TOKENS_TOTAL = Counter("llm_prompt_tokens_total", "Prompt tokens sent to the LLM", labelnames=("model",))
LLM_COMPLETION_TOKENS_TOTAL = Counter(
    "llm_completion_tokens_total", "Completion tokens generated by the LLM", labelnames=("model",)
)

# The dedup optimization, quantified: LLM calls the short-circuit avoided. Each cache
# hit skips the whole LLM section of the pipeline (the 6 LLM stages below).
LLM_STAGES = 6  # semantic_enrichment, taxonomy, sentiment, signals, risk, executive
LLM_CALLS_SAVED_TOTAL = Counter(
    "llm_calls_saved_total",
    "Estimated LLM calls avoided by the dedup short-circuit (LLM_STAGES per cache hit)",
)

# Calibration / active-learning: the confidence distribution and the review rate.
PIPELINE_CONFIDENCE = Histogram(
    "pipeline_confidence",
    "Distribution of pipeline_confidence over computed analyses",
    buckets=_UNIT_BUCKETS,
)
NEEDS_REVIEW_TOTAL = Counter(
    "needs_review_total",
    "Analyses flagged (low confidence) and enqueued for human review",
)


@contextmanager
def stage_timer(stage: str):
    """Record the wall time of a `with` block into the per-stage histogram."""
    start = time.perf_counter()
    try:
        yield
    finally:
        PIPELINE_STAGE_DURATION.labels(stage=stage).observe(time.perf_counter() - start)


def timed_stage(name: str, runnable):
    """Wrap an LCEL runnable so each invocation records into PIPELINE_STAGE_DURATION.

    Returns a RunnableLambda preserving the dict-in/dict-out contract, so it composes
    with `|` exactly like the original stage.
    """
    from langchain_core.runnables import RunnableLambda

    def _invoke(ctx: dict) -> dict:
        with stage_timer(name):
            return runnable.invoke(ctx)

    return RunnableLambda(_invoke)
